# Generated by Django 4.0.3 on 2022-03-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
